### ISSUE TITLE
Not Detecting BTC

### ISSUE THREAD

**Issue by prodplug** [DarrenWestwood/greed#30]
So I tested my bot on a fake account and paid, even after the BTC is confirmed on Blockonomics and after using the /start command again, the balance isn't updated. any fix?

**Comment by DarrenWestwood** [comment]
This error is most likely caused by the Blockonomics http callback request not reaching your public callback url correctly. Please check the Blockonomics callback logs to verify the callback successfully reached your callback url. The logs can be located from the [Blockonomics Logs / Test Bench](https://www.blockonomics.co/merchants#/logs).

If you require further assistance please open a ticket with the Blockonomics support team in order for us to take a look at your account and check your callback logs:
https://help.blockonomics.co/support/tickets/new

**Comment by DarrenWestwood** [comment]
The bot has been updated to use a polling system instead of callbacks. This allows you to fully test the functionality of the Bot using the Blockonomics [Test Bench](https://www.blockonomics.co/merchants#/logs), and no longer requires a public callback url. Feel free to test the latest version, which should update the balance correctly now.
