### ISSUE TITLE
SQL Issue

### ISSUE THREAD

**Issue by manifestukz** [DarrenWestwood/greed#37]
Hi,

I am getting errors such as

 sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: btc_transactions
2022-05-21T18:00:36.311584+00:00 app[web.1]: [SQL: SELECT btc_transactions.transaction_id AS btc_transactions_transaction_id, btc_transactions.user_id AS btc_transactions_user_id, btc_transactions.price AS btc_transactions_price, btc_transactions.value AS btc_transactions_value, btc_transactions.currency AS btc_transactions_currency, btc_transactions.status AS btc_transactions_status, btc_transactions.timestamp AS btc_transactions_timestamp, btc_transactions.address AS btc_transactions_address, btc_transactions.txid AS btc_transactions_txid
2022-05-21T18:00:36.311585+00:00 app[web.1]: FROM btc_transactions
2022-05-21T18:00:36.311585+00:00 app[web.1]: WHERE btc_transactions.address = ?]

How do I fix this?

**Comment by DarrenWestwood** [comment]
There appears to be an issue with the btc_transactions table in the database. https://github.com/DarrenWestwood/greed/blob/master/core.py#L79 should check for missing tables, however there still appears to be some issue. 
I will try replicating this issue on my end. Please let me know the following information, in order to help diagnose this issue as efficiently as possible:
1) Are you using the latest files from this github repository: https://github.com/DarrenWestwood/greed?
2) Is the btc_transactions table present in the SQLite database?
![greed-db](https://user-images.githubusercontent.com/39666372/170002844-9455e27b-bcc3-4748-b59a-8e9cd88b4c2d.png)

**Comment by manifestukz** [comment]
Thanks Darren fixed,

May you make a "Check Funds" button to ensure no stuck btc is left on the system? Thanks...

**Comment by DarrenWestwood** [comment]
I am glad to hear you managed to resolve the issue.

> May you make a "Check Funds" button to ensure no stuck btc is left on the system?

Blockonomics payments go directly to bitcoin addresses from your bitcoin wallet. Please can you explain the desired functionality of the Check Funds button.

**Comment by manifestukz** [comment]
> I am glad to hear you managed to resolve the issue.
> 
> > May you make a "Check Funds" button to ensure no stuck btc is left on the system?
> 
> Blockonomics payments go directly to bitcoin addresses from your bitcoin wallet. Please can you explain the desired functionality of the Check Funds button.

Hi,

Please can you implement the part to stop the GAP limit issue? If 20 people enter and request a payment, GAP limit will display in my inbox causing payment system to crash. Thanks.

**Comment by DarrenWestwood** [comment]
The gap limit is a limitation depending on the bitcoin wallet you are currently using. You can increase the gap limit by using Electrum wallet with Blockonomics, and increasing the gap limit using the following instructions:
https://help.blockonomics.co/support/solutions/articles/33000215760-gap-limit-faq#electrum

Feel free to let me know if you have any further questions regarding increasing the gap limit and I will be happy to assist you further.
