### ISSUE TITLE
 callback request 404 error

### ISSUE THREAD

**Issue by Czeslaw102** [DarrenWestwood/greed#45]
I send test payment by blockonomics and in logs got a 404 error:
[Sep 16,2022 00:11:07][ http://6.eu.ngrok.io/iocallback?secret=XXX&addr=XXX&status=2&txid=WarningThisIsAGeneratedTestPaymentAndNotARealBitcoinTransaction&value=507112](http:7.eu.ngrok.io/iocallback?secret=XXX&addr=XXX&status=2&txid=WarningThisIsAGeneratedTestPaymentAndNotARealBitcoinTransaction&value=507112) 404

Logs from callback.py
127.0.0.1 - - [16/Sep/2022 00:06:43] "GET /iocallback?secret=XXX&status=0&addr=XXXX&value=127287&txid=WarningThisIsAGeneratedTestPaymentAndNotARealBitcoinTransaction HTTP/1.1" 404 -

**Comment by DarrenWestwood** [comment]
Hi @Czeslaw102,

Your callback URL (http://6.eu.ngrok.io/iocallback?secret=XXX) appears to be incorrect, which is why you are receiving the 404 (Not Found) error.

Please ensure you include the _full ngrok url_, _/callback_ path, and _secret_ parameter in the url as shown below:
http://c7f7ecb92ht5.ngrok.io/callback?secret=XXX

The HTTP Callback URL can be updated on your Blockonomics store to fix future callbacks: https://www.blockonomics.co/merchants#/stores

Kind regards

**Comment by Czeslaw102** [comment]
I have censored the full link, in fact I don't know why, 
the full link is:
[Sep 16,2022 00:11:07] http://6f28-92-23-11-97.eu.ngrok.io/iocallback?secret=XXX&addr=bc1qz894k2vcmzvpwwn9m0rptrqu236jescdmjgtd6&status=2&txid=WarningThisIsAGeneratedTestPaymentAndNotARealBitcoinTransaction&value=507112 404

**Comment by DarrenWestwood** [comment]
The full link posted includes an additional 'io' in the path. Please use the following Callback URL to verify this solves your issue:
http://6f28-92-23-11-97.eu.ngrok.io/callback?secret=XXX

**Comment by Czeslaw102** [comment]
Oh good, Im so so stupid, of course its working now, thank you brother!
