### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by skintgang1** [DarrenWestwood/greed#46]
Is this still working? I tried so much, the callback request seems not to work, even when I test transaction it still doesn't say it's in the balance. I'm not sure what to do here

**Comment by DarrenWestwood** [comment]
Hi @skintgang1,

>Is this still working? I tried so much, the callback request seems not to work, even when I test transaction it still doesn't say it's in the balance. I'm not sure what to do here

Yes bitcoin payments are still working and actively updated. You can test callback requests using the [Blockonomics Test Bench](https://www.blockonomics.co/merchants#/logs) without spending bitcoin and use [this article](https://help.blockonomics.co/support/solutions/articles/33000219539-order-status-not-changing-callbacks-failing) to diagnose issues with Blockonomics callbacks reaching your bot:
https://www.youtube.com/watch?v=hZ4rwTp4Oc8
The status of the callback request should be 200 in the Blockonomics callback logs if the request successfully reaches your bots callback url. 

Please feel free to open a new ticket with [Blockonomics support](https://help.blockonomics.co/support/tickets/new) in order to check your logs and verify your callback url is setup correctly.

Kind regards
