### ISSUE TITLE
Flood Control

### ISSUE THREAD

**Issue by jashvakharia** [DarrenWestwood/greed#69]
Whenever i try to start the bot, it gives an error of flood control. please see the issue.

**Comment by DarrenWestwood** [comment]
Hi @jashvakharia,

The bot installation and startup is working correctly on my end without any errors. I will require more information regarding the error in order to assist you further, however, I recommend re-installing the bot in a new python venv with the default bot configuration.

If this does not help, please share the full error logs and current setup you are using.

Kind regards

**Comment by jashvakharia** [comment]
i am using WSL, and the error is this like

“starting bot”

i did the /start thing

“unable to send message, flood control”

**Comment by jashvakharia** [comment]
https://katb.in/odogazoqese

this is the full error.

**Comment by jashvakharia** [comment]
hi @DarrenWestwood , kindly look into it.
